services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db-wordpress.cqhgoqakquv7.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: tGen1oeTA6DAVd0Zuy80
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - /efs/data:/var/www/html