services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db-wordpress.cqhgoqakquv7.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: cgGRL34X1qFqTVkWDlrR
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - /efs/data:/var/www/html